name: Generate Keystore (one-time)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore boost-release.keystore \
            -alias boost \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "pawaKely0143!" \
            -keypass "pawaKely0143!" \
            -dname "CN=Hery, OU=BOOST, O=BOOST, L=Antananarivo, S=Analamanga, C=MG"

      - name: Show SHA-256 fingerprint
        run: |
          keytool -list -v -keystore boost-release.keystore -alias boost -storepass "ChangeThisPassword123!"

      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v4
        with:
          name: boost-release-keystore
          path: boost-release.keystore
          retention-days: 7
